#! /bin/sh

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $PASS_CORE_DATABASE_USERNAME WITH PASSWORD '$PASS_CORE_DATABASE_PASSWORD';
	CREATE DATABASE pass;
	GRANT ALL PRIVILEGES ON DATABASE pass TO $PASS_CORE_DATABASE_USERNAME;
EOSQL
